from PyQt6 import QtCore, QtGui, QtWidgets
import sys, res_mod_rc


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(763, 588)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.minimizedbar = QtWidgets.QWidget(parent=self.centralwidget)
        self.minimizedbar.setGeometry(QtCore.QRect(0, 10, 71, 571))
        self.minimizedbar.setObjectName("minimizedbar")
        self.layoutWidget = QtWidgets.QWidget(parent=self.minimizedbar)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 45, 203))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.icon1 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.icon1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.icon1.setIcon(icon)
        self.icon1.setIconSize(QtCore.QSize(31, 54))
        self.icon1.setObjectName("icon1")
        self.verticalLayout_2.addWidget(self.icon1)
        self.home_btn = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.home_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("home.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.home_btn.setIcon(icon1)
        self.home_btn.setIconSize(QtCore.QSize(23, 35))
        self.home_btn.setCheckable(True)
        self.home_btn.setAutoExclusive(True)
        self.home_btn.setObjectName("home_btn")
        self.verticalLayout_2.addWidget(self.home_btn)
        self.dashboard_btn = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.dashboard_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("dashboard.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.dashboard_btn.setIcon(icon2)
        self.dashboard_btn.setIconSize(QtCore.QSize(23, 35))
        self.dashboard_btn.setCheckable(True)
        self.dashboard_btn.setAutoExclusive(True)
        self.dashboard_btn.setObjectName("dashboard_btn")
        self.verticalLayout_2.addWidget(self.dashboard_btn)
        self.settings_btn = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.settings_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("settings.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.settings_btn.setIcon(icon3)
        self.settings_btn.setIconSize(QtCore.QSize(23, 35))
        self.settings_btn.setCheckable(True)
        self.settings_btn.setAutoExclusive(True)
        self.settings_btn.setObjectName("settings_btn")
        self.verticalLayout_2.addWidget(self.settings_btn)
        self.widget = QtWidgets.QWidget(parent=self.minimizedbar)
        self.widget.setGeometry(QtCore.QRect(20, 210, 37, 357))
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 308, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.exit_btn = QtWidgets.QPushButton(parent=self.widget)
        self.exit_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("exit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.exit_btn.setIcon(icon4)
        self.exit_btn.setIconSize(QtCore.QSize(23, 35))
        self.exit_btn.setCheckable(True)
        self.exit_btn.setAutoExclusive(True)
        self.exit_btn.setObjectName("exit_btn")
        self.verticalLayout_3.addWidget(self.exit_btn)
        self.mainpage = QtWidgets.QWidget(parent=self.centralwidget)
        self.mainpage.setGeometry(QtCore.QRect(230, 10, 551, 571))
        self.mainpage.setObjectName("mainpage")
        self.login_btn = QtWidgets.QPushButton(parent=self.mainpage)
        self.login_btn.setGeometry(QtCore.QRect(40, 190, 131, 111))
        self.login_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("user.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.login_btn.setIcon(icon5)
        self.login_btn.setIconSize(QtCore.QSize(76, 74))
        self.login_btn.setObjectName("login_btn")
        self.signup_btn = QtWidgets.QPushButton(parent=self.mainpage)
        self.signup_btn.setGeometry(QtCore.QRect(350, 190, 121, 111))
        self.signup_btn.setStyleSheet("")
        self.signup_btn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("new_user.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.signup_btn.setIcon(icon6)
        self.signup_btn.setIconSize(QtCore.QSize(75, 79))
        self.signup_btn.setObjectName("signup_btn")
        self.widget1 = QtWidgets.QWidget(parent=self.mainpage)
        self.widget1.setGeometry(QtCore.QRect(10, 10, 514, 43))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sidebar_btn = QtWidgets.QPushButton(parent=self.widget1)
        self.sidebar_btn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("sidebar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.sidebar_btn.setIcon(icon7)
        self.sidebar_btn.setIconSize(QtCore.QSize(23, 22))
        self.sidebar_btn.setCheckable(True)
        self.sidebar_btn.setAutoExclusive(False)
        self.sidebar_btn.setObjectName("sidebar_btn")
        self.horizontalLayout.addWidget(self.sidebar_btn)
        spacerItem1 = QtWidgets.QSpacerItem(118, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.searchbox = QtWidgets.QLineEdit(parent=self.widget1)
        self.searchbox.setObjectName("searchbox")
        self.horizontalLayout.addWidget(self.searchbox)
        self.search_btn = QtWidgets.QPushButton(parent=self.widget1)
        self.search_btn.setText(" ")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("search.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.search_btn.setIcon(icon8)
        self.search_btn.setIconSize(QtCore.QSize(22, 15))
        self.search_btn.setCheckable(True)
        self.search_btn.setAutoExclusive(True)
        self.search_btn.setObjectName("search_btn")
        self.horizontalLayout.addWidget(self.search_btn)
        spacerItem2 = QtWidgets.QSpacerItem(118, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.profile_btn = QtWidgets.QPushButton(parent=self.widget1)
        self.profile_btn.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("user_login.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.profile_btn.setIcon(icon9)
        self.profile_btn.setIconSize(QtCore.QSize(23, 35))
        self.profile_btn.setCheckable(True)
        self.profile_btn.setAutoExclusive(True)
        self.profile_btn.setObjectName("profile_btn")
        self.horizontalLayout.addWidget(self.profile_btn)
        self.expandedbar = QtWidgets.QWidget(parent=self.centralwidget)
        self.expandedbar.setGeometry(QtCore.QRect(70, 10, 131, 571))
        self.expandedbar.setObjectName("expandedbar")
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.expandedbar)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 114, 191))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.icon2 = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.icon2.setIcon(icon)
        self.icon2.setIconSize(QtCore.QSize(30, 40))
        self.icon2.setObjectName("icon2")
        self.verticalLayout.addWidget(self.icon2)
        self.home_btn2 = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.home_btn2.setIcon(icon1)
        self.home_btn2.setIconSize(QtCore.QSize(15, 18))
        self.home_btn2.setCheckable(True)
        self.home_btn2.setAutoExclusive(True)
        self.home_btn2.setObjectName("home_btn2")
        self.verticalLayout.addWidget(self.home_btn2)
        self.dashboard_btn2 = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.dashboard_btn2.setIcon(icon2)
        self.dashboard_btn2.setIconSize(QtCore.QSize(22, 18))
        self.dashboard_btn2.setCheckable(True)
        self.dashboard_btn2.setAutoExclusive(True)
        self.dashboard_btn2.setObjectName("dashboard_btn2")
        self.verticalLayout.addWidget(self.dashboard_btn2)
        self.settings_btn2 = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.settings_btn2.setIcon(icon3)
        self.settings_btn2.setIconSize(QtCore.QSize(18, 15))
        self.settings_btn2.setCheckable(True)
        self.settings_btn2.setAutoExclusive(True)
        self.settings_btn2.setObjectName("settings_btn2")
        self.verticalLayout.addWidget(self.settings_btn2)
        self.widget2 = QtWidgets.QWidget(parent=self.expandedbar)
        self.widget2.setGeometry(QtCore.QRect(10, 190, 82, 370))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(20, 338, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.exit_btn2 = QtWidgets.QPushButton(parent=self.widget2)
        self.exit_btn2.setIcon(icon4)
        self.exit_btn2.setIconSize(QtCore.QSize(19, 18))
        self.exit_btn2.setCheckable(True)
        self.exit_btn2.setAutoExclusive(True)
        self.exit_btn2.setObjectName("exit_btn2")
        self.verticalLayout_4.addWidget(self.exit_btn2)
        #MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.sidebar_btn.toggled['bool'].connect(self.expandedbar.setHidden) # type: ignore
        #self.sidebar_btn.toggled['bool'].connect(self.minimizedbar.setVisible) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.icon2.setText(_translate("MainWindow", " Side Bar"))
        self.home_btn2.setText(_translate("MainWindow", " Home"))
        self.dashboard_btn2.setText(_translate("MainWindow", " Dashboard"))
        self.settings_btn2.setText(_translate("MainWindow", " Settings"))
        self.exit_btn2.setText(_translate("MainWindow", "Exit"))

if __name__ == "__main__":
        app = QtWidgets.QApplication(sys.argv)
        Form = QtWidgets.QWidget()
        ui = Ui_MainWindow()
        ui.setupUi(Form)
        Form.show()
        sys.exit(app.exec())